# Generated by Django 4.2 on 2023-04-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salacrypto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100)),
                ('power', models.IntegerField(default=0, max_length=6)),
                ('level', models.IntegerField(default=0, max_length=3)),
                ('codex', models.IntegerField(default=0, max_length=4)),
            ],
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='Cla',
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='Classe',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='player',
            name='cla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salacrypto_app.cla'),
        ),
        migrations.AddField(
            model_name='player',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salacrypto_app.classe'),
        ),
    ]
