# Generated by Django 4.2 on 2023-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salacrypto_app', '0002_player_rename_department_cla_rename_role_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='codex',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='power',
            field=models.IntegerField(max_length=6),
        ),
    ]
