# Generated by Django 4.2 on 2023-04-13 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salacrypto_app', '0003_alter_player_codex_alter_player_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='codex',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='power',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
